### 查询服务
GET http://127.0.0.1:9000/laishishui/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commmerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwi5byg5LiJXCJ9IiwianRpIjoiYTJjODkwNzEtZWM5NS00N2JmLThiMGYtZWI4ZjQxOTUwMGEwIiwiZXhwIjoxNjU0NzA0MDAwfQ.mLjYHFQfcq7h_qmaP2Gjzqf2qI7L09guWS_LbxoYNQzUuB1m_L4aaVf1ExoQvV_UqaIpYqWzKm6J19PM3-SNeHm6q9naPVH6IaiwiaqLUGRL-z7PzfGYBir6inhWLNcD5BPmjGYfep-w_poLeorYeq-e784Tg90oEGoLnYkRTdS19eOH2bug2cftG7745KnEteYtBVA8AE16EHTdV4lybv_yawQjMVsPoJTCs2Wp8PpW84lOGXK1QGpqxNdVyiDS9jmIRGaGlXjsswfX4FrM0I827zOaMMkIaqNc8TlDaWxPKO_ZwgC3WZa2Mus3ffH4ma35wyie5gtsnosLYX8hbQ
token: laishishui