### 创建订单
POST http://127.0.0.1:9000/laishishui/ecommerce-order-service/order/create-order
Content-Type: application/json
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwi5byg5LiJXCJ9IiwianRpIjoiMjA4NmViOWUtNGM0Yy00MjA3LThkMTYtZDRjYTU1N2JiZmY5IiwiZXhwIjoxNjU1NzQwODAwfQ.pGbKeFjHJGIenAEqFowweVDxvhe39X1Cef7FxAagD-6528HewkyS_NfRs3_GAFePAdPd16HtApGD64f2VFZlcpcLQ0AYbeYUDIXQvEchXCnw1wMapGMtAm3Ub59NNuw5kvgcOkaCp9IUGlMRtS_0bnN1PZAs-3YLGfgLOv_saq_bsu4ZxAMluw4EiGmV3Dr3KP5_qbrit6FLP9rF1M35c0KR9k_3XG88hd2dK8IiDk2O2zqug-wZPQglsFWpiaSSZSLIwRZkxuI5dpsb8cVWNOuMuSTtY6oPG4Y7pXqVPlNKVgQVtAHR4zovbQG0FHLOQSsVXjhf3Zms5YsYlYfhjw
{
  "userAddress": 1,
  "orderItems": [
    {
      "goodsId": 1,
      "count": 5
    }
  ]
}

### 查询订单
GET http://127.0.0.1:9000/laishishui/ecommerce-order-service/order/order-detail?page=2
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwi5byg5LiJXCJ9IiwianRpIjoiMjA4NmViOWUtNGM0Yy00MjA3LThkMTYtZDRjYTU1N2JiZmY5IiwiZXhwIjoxNjU1NzQwODAwfQ.pGbKeFjHJGIenAEqFowweVDxvhe39X1Cef7FxAagD-6528HewkyS_NfRs3_GAFePAdPd16HtApGD64f2VFZlcpcLQ0AYbeYUDIXQvEchXCnw1wMapGMtAm3Ub59NNuw5kvgcOkaCp9IUGlMRtS_0bnN1PZAs-3YLGfgLOv_saq_bsu4ZxAMluw4EiGmV3Dr3KP5_qbrit6FLP9rF1M35c0KR9k_3XG88hd2dK8IiDk2O2zqug-wZPQglsFWpiaSSZSLIwRZkxuI5dpsb8cVWNOuMuSTtY6oPG4Y7pXqVPlNKVgQVtAHR4zovbQG0FHLOQSsVXjhf3Zms5YsYlYfhjw
